// =====================
// COUNTRY LIST
// =====================
// List of countries for autocomplete (countries only, no cities)

export const countries = [
  'United States',
  'Canada',
  'United Kingdom',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Portugal',
  'Greece',
  'Ireland',
  'Czech Republic',
  'Romania',
  'Hungary',
  'Bulgaria',
  'Croatia',
  'Slovakia',
  'Slovenia',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Japan',
  'China',
  'India',
  'South Korea',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Malaysia',
  'Singapore',
  'Taiwan',
  'Hong Kong',
  'Australia',
  'New Zealand',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Venezuela',
  'Ecuador',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Costa Rica',
  'Panama',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Dominican Republic',
  'Cuba',
  'Jamaica',
  'Haiti',
  'Trinidad and Tobago',
  'Bahamas',
  'Barbados',
  'Russia',
  'Ukraine',
  'Turkey',
  'Saudi Arabia',
  'United Arab Emirates',
  'Israel',
  'Egypt',
  'Iran',
  'Iraq',
  'Jordan',
  'Lebanon',
  'Syria',
  'Kuwait',
  'Qatar',
  'Oman',
  'Yemen',
  'Bahrain',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Ethiopia',
  'Tanzania',
  'Uganda',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Libya',
  'Sudan',
  'Angola',
  'Mozambique',
  'Madagascar',
  'Cameroon',
  'Ivory Coast',
  'Senegal',
  'Zimbabwe',
  'Zambia',
  'Malawi',
  'Rwanda',
  'Benin',
  'Burkina Faso',
  'Mali',
  'Niger',
  'Chad',
  'Mauritania',
  'Guinea',
  'Sierra Leone',
  'Liberia',
  'Togo',
  'Gabon',
  'Botswana',
  'Namibia',
  'Mauritius',
  'Eswatini',
  'Lesotho',
  'Pakistan',
  'Bangladesh',
  'Afghanistan',
  'Sri Lanka',
  'Nepal',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Mongolia',
  'Kazakhstan',
  'Uzbekistan',
  'Kyrgyzstan',
  'Tajikistan',
  'Turkmenistan',
  'Azerbaijan',
  'Armenia',
  'Georgia',
  'Belarus',
  'Moldova',
  'Albania',
  'Bosnia and Herzegovina',
  'Serbia',
  'Montenegro',
  'North Macedonia',
  'Kosovo',
  'Iceland',
  'Greenland',
  'Fiji',
  'Papua New Guinea',
  'Solomon Islands',
  'Vanuatu',
  'Samoa',
  'Tonga',
  'Palau',
  'Micronesia',
  'Marshall Islands',
  'Kiribati',
  'Tuvalu',
  'Nauru',
];

/**
 * Filter countries by search query (case-insensitive)
 */
export function filterCountries(query: string): string[] {
  if (!query || query.length < 1) {
    return countries.slice(0, 10); // Return first 10 if no query
  }
  
  const lowerQuery = query.toLowerCase();
  return countries
    .filter(country => country.toLowerCase().includes(lowerQuery))
    .slice(0, 10); // Limit to 10 results
}

